services:
  container:
    build: docker
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - DISPLAY
      - NVIDIA_DRIVER_CAPABILITIES=all
      - XDG_RUNTIME_DIR=/tmp/runtime-xdg_runtime_dir
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d:ro
      - /usr/share/vulkan/implicit_layer.d:/usr/share/vulkan/implicit_layer.d:ro
      # - /usr/share/vulkan/explicit_layer.d/VkLayer_INTEL_nullhw.json:/usr/share/vulkan/explicit_layer.d/VkLayer_INTEL_nullhw.json:ro
      # - /usr/share/vulkan/explicit_layer.d/VkLayer_MESA_overlay.json:/usr/share/vulkan/explicit_layer.d/VkLayer_MESA_overlay.json:ro
      - .:/workspaces/vulkan-tutorial:cached
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
